name: Github action to install Docker on self hosted ubuntu machine

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Checkout Repository
      uses: actions/setup-python@v2

    - name: Install dependencies for python
      run: |
       sudo apt update
       sudo apt install docker.io -y
       sudo usermod -aG docker $USER
       newgrp docker
    - name: Verfiy the docker installation
      run: |
        docker --version
    - name: Pull Nginx image
      run: |
        docker pull nginx:latest
        docker run -p 80:80 -d -it nginx:latest
