name: Github action to run jenkins using docker image

on:
  push:
    paths:
      'jenkins.yaml'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Checkout Repository
      uses: actions/setup-python@v2

    - name: Verfiy the docker installation
      run: |
        docker --version
    - name: Pull Jenkins image and run
      run: |
        docker pull jenkins/jenkins:lts-jdk17
        docker run -d -p 8080:8080 -p 5000:5000 -it -v jenkins_home:/var/jenkins_home --restart=on-failure jenkins/jenkins:lts-jdk17
        
